sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: QUmrIwo70dess7hynYiKY1PVHAedkErsTM57DtlzZ4236Zkr6UgjzYOASAg23fh9lAVROctPurRUuEakV+dW5fSRBJOmZvR/7rUIZGBkm+fxhobbvCyd6muaRGxVhHSHM5hXNg9Ib9t7jio5D+RRNBo9h0vU2vlV5nzTrTJfnowmI0b9mqgktQ7gBsLjvjD9QRWLs+wxze9zod3YTM55whsHrbu3o5hI5mS6mya9ZX8HeS4r++c93TGbAd+/SErVAzUSzybiDvN2bFIoJlBAo5XaupZ2o8kD5/m4mbrE6FGGx8FM4QP4JSP+3De1VI/OcbVQ+Uzcy0n+nCgSqRv5wQkwgqbFMNTFIOMMB5abLH5f2TTrfUs9sgR/U/DN6DV62rlXSXVaFIXXHvnMLONKJCksRX0syQ4jSOxuZAyO05YozkKl2qn/mJfPJ5XkhtF0TIKrR7HRBifSHU0ZXQ2WeajCqM/hkWpARJuKBVLjUCY24AiLTN3tpG7zR4PRV0YzJIzgshyqI1ycsU0ITxdzRT5PPBOnMGixRUR7mikpvboOdmANsmQHFzcQnyrSrRVr256h4KChX5Pkfwxk8xNwStyWnFt31QNfxv08EL19Bbx+ve3GhzKHBJbREckUJi9XRu57xA+DggHAtRdQY7rrtYMUpGInL/Bib/ywMwW1n/M=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Smoke-Bellew_5737
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy